In [1]:
import pandas as pd

1. Завантаження та огляд

Завантажте датасет Tips (Чайові) з файла у матеріалах tips.csv.

Виведіть (кожен пункт оцінюється в 0.5 бала):

Перші 5 рядків
Розмір датасету (shape)
Назви всіх колонок
Інформацію про типи даних (info)

In [2]:
df = pd.read_csv('tip.csv')

In [3]:
display (df.head(5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
display(df.shape)

(244, 7)

In [5]:
display (df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [13]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

2. Базова вибірка даних

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):

Колонку total_bill (загальний рахунок)
Колонки total_bill та tip (чайові) разом
Перші 10 рядків
Рядок з індексом 5

In [14]:
total_bill=df['total_bill']
print (total_bill)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [8]:
selected=df[['total_bill','tip']]
print(selected)

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [9]:
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [10]:
print (df.iloc[5])

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

3. Фільтрація даних

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):

Всі рахунки більше 20 доларів (total_bill > 20)
Всі відвідувачі-жінки (sex == 'Female')
Рахунки на вечерю (time == 'Dinner')
Рахунки на вечерю з сумою чеку більше 30 доларів
Для виведення результатів фільтрації:

зберегти результат у окрему змінну
показати кількість записів у відфільтрованому наборі
вивести перші 5 записів відфільтрованого набору.

In [15]:
amount_1=df[(df['total_bill']>20)] #Всі рахунки більше 20 доларів
print(amount_1)

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [16]:
amount_1.shape

(97, 7)

In [17]:
amount_1.head()

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [ ]:
female_df=df[(df['sex']=='Female')] #Всі відвідувачі-жінки
print (female)

In [ ]:
female_df.shape

In [ ]:
female.head()

In [ ]:
time_df=df[(df['time']=='Dinner')] #Рахунки на вечерю
print(time_df)

In [ ]:
time_df.shape

In [ ]:
time_df.head()

In [22]:
amount_2=df[(df['total_bill']>30)&(df['time'] == 'Dinner')] #Рахунки на вечерю з сумою чеку більше 30 доларів
print(amount_2)

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

In [23]:
amount_2.shape

(27, 7)

In [24]:
amount_2.head ()

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [ ]:
4. Описова статистика

Обчисліть (кожен пункт оцінюється в 0.5 бала):

Середній розмір рахунку на всьому наборі даних
Максимальні чайові
Кількість пропущених значень у всіх колонках
Скільки в наборі даних рахунків за обіди і за вечері

In [27]:
avg_bill = df['total_bill'].mean() #Середній розмір рахунку на всьому наборі даних
print(avg_bill)

19.78594262295082

In [29]:
max_tip = df['tip'].max() #Максимальні чайові
print(max_tip)

10.0

In [46]:
df.isnull().sum() #Кількість пропущених значень у всіх колонках

total_bill        0
tip               0
sex               0
smoker            0
day               0
time              0
size              0
tip_percentage    0
dtype: int64

In [50]:
meal_counts = df['time'].value_counts() #Скільки в наборі даних рахунків за обіди і за вечері
meal_counts

time
Dinner    176
Lunch      68
Name: count, dtype: int64

5. Статистика із групуванням

Обчисліть (кожен пункт оцінюється в 0.5 бала):

Середній рахунок за статтю (groupby sex)
Середні чайові за днем тижня (groupby day)
Скільки відвідувачів у кожен день

In [47]:
avg_bill_by_sex = df.groupby('sex')['total_bill'].mean() #Середній рахунок за статтю (groupby sex)
print('Середній чек за статтю')
avg_bill_by_sex

Середній чек за статтю

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [48]:
avg_tip_by_day = df.groupby('day')['tip'].mean() #Середні чайові за днем тижня (groupby day)
print ('Середні чайові по днях')
avg_tip_by_day

Середні чайові по днях

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [49]:
visitors_by_day = df['day'].value_counts() #Скільки відвідувачів у кожен день
print ('Кількість відвідувачів по днях тижня')
visitors_by_day

Кількість відвідувачів по днях тижня

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

6. Створення нової колонки

Створіть нову колонку tip_percentage - відсоток чайових від загальної суми рахунку. Виведіть перші 10 рядків з новою колонкою.

In [39]:
df['tip_percentage'] = (df['tip'] / df['total_bill']*100).round(2) #Створіть нову колонку tip_percentage - відсоток чайових... (з округленням!)
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68
5       25.29  4.71    Male     No  Sun  Dinner     4           18.62
6        8.77  2.00    Male     No  Sun  Dinner     2           22.81
7       26.88  3.12    Male     No  Sun  Dinner     4           11.61
8       15.04  1.96    Male     No  Sun  Dinner     2           13.03
9       14.78  3.23    Male     No  Sun  Dinner     2           21.85

In [40]:
df.shape #тепер в нас 8 колонок

(244, 8)

7. Сортування

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):

За розміром рахунку (зростання)
За чайовими (спадання)
Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.

In [41]:
sorted_by_bill = df.sort_values(by='total_bill', ascending=True)
sorted_by_bill.head()

     total_bill   tip     sex smoker   day    time  size  tip_percentage
67         3.07  1.00  Female    Yes   Sat  Dinner     1           32.57
92         5.75  1.00  Female    Yes   Fri  Dinner     2           17.39
111        7.25  1.00  Female     No   Sat  Dinner     1           13.79
172        7.25  5.15    Male    Yes   Sun  Dinner     2           71.03
149        7.51  2.00    Male     No  Thur   Lunch     2           26.63

In [43]:
sorted_by_tip = df.sort_values(by='tip', ascending=False)
sorted_by_tip.head()

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53

In [44]:
top_5_tips = df.nlargest(5, 'tip')
top_5_tips

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53